### ISSUE TITLE
The GPU and Training time

### ISSUE THREAD

**Issue by AN-AN-369** [JiarunLiu/Swin-UMamba#1]
Your innovation with Mamba is amazing. I would like to ask you about your equipment and the time of a training session.

**Comment by JiarunLiu** [comment]
Hi @AN-AN-369,

Thanks for your interest.

We use A800 GPU to train Swin-UMamba. The training time depends on the dataset and the number of epochs. In our experiments, it took about:
- 3 hours on AbdomenMRI (100 epochs)
- 12.5 hours on Endoscopy (250 epochs)
- 16 hours on Microscopy (350 epochs)
