### ISSUE TITLE
How do you calculate FLOPs?

### ISSUE THREAD

**Issue by Kim-yhao** [JiarunLiu/Swin-UMamba#11]
Please tell me where is the code used to calculate FLOPs? Or can you tell me what is the shape of the input used to calculate FLOPs?

**Comment by Kim-yhao** [comment]
I tested my Swin-UMamba using thop.profile() and an image with shape (3, 224, 224), and the result was 4.4 GFLOPs, which is a big difference between your result.

**Comment by JiarunLiu** [comment]
Hi @Kim-yhao, we use [fvcore](https://github.com/facebookresearch/fvcore) to calculate FLOPs with the code from this [issue](https://github.com/state-spaces/mamba/issues/110). The shape of the input varies across different datasets:
- AbdomenMRI: (1, 320, 320)
- Endoscopy: (3, 384, 640)
- Microscopy: (3, 512, 512)

**Comment by Weixiang-Sun** [comment]
> Hi @Kim-yhao, we use [fvcore](https://github.com/facebookresearch/fvcore) to calculate FLOPs with the code from this [issue](https://github.com/state-spaces/mamba/issues/110). The shape of the input varies across different datasets:
> 
> * AbdomenMRI: (1, 320, 320)
> * Endoscopy: (3, 384, 640)
> * Microscopy: (3, 512, 512)

Could you release the py file to calculate this in your project? thank you
