### ISSUE TITLE
issues with installing causal-convd1 and mamba-ssm

### ISSUE THREAD

**Issue by tash46** [JiarunLiu/Swin-UMamba#12]
Thank you for your hard work. I'm really interested in your model.
I hope this issue finds you well.
I'm currently struggling with installing causal-convd1 and mamba-SSM; the attached photos are respectively.
My nvidia-smi and nvcc-V are matching with cuda 11.7 but still have problem installing them.
![스크린샷 2024-05-17 091131](https://github.com/JiarunLiu/Swin-UMamba/assets/163090779/3afb8216-755a-4c32-be55-108fc1156587)
![스크린샷 2024-05-17 090821](https://github.com/JiarunLiu/Swin-UMamba/assets/163090779/430d55d2-c0b5-4a73-ba2d-27dba8171914)

Are these two mandatory to run Swin-UMamba model? If so, please let me know if you have any solution for this issue.
Thank you.

**Comment by JiarunLiu** [comment]
Hi @tash46. We use `ubuntu 22.04 LTS` + `nvidia-smi==535.161.07` + `cuda 12.2` on our server. I found an similar [issue](https://github.com/state-spaces/mamba/issues/55) from [mamba](https://github.com/state-spaces/mamba). Hope it helps.

**Comment by tash46** [comment]
Are those answers from the issue helpful?

**Comment by JiarunLiu** [comment]
@tash46 You can try it. We have never encountered this issue before.
