### ISSUE TITLE
请问网络模型在哪个文件夹下？

### ISSUE THREAD

**Issue by 1580827935** [JiarunLiu/Swin-UMamba#2]

**Comment by JiarunLiu** [comment]
Hi @1580827935,

预训练模型和Swin-UMamba所对应的下载链接和文件路径如下: 
- pretrained model ([link](https://github.com/MzeroMiko/VMamba/releases/download/%2320240218/vssmtiny_dp01_ckpt_epoch_292.pth)): `data/pretrained/vmamba/vmamba_tiny_e292.pth`
- Swin-UMamba ([link](https://drive.google.com/drive/folders/1Sb8c1k556jFw6jwASttji1ofprh1MbP0?usp=drive_link)): `data/nnUNet_results/`

**Comment by 1580827935** [comment]
感谢

**Comment by 1580827935** [comment]
BUG! 请问这个包是在哪？
![111](https://github.com/JiarunLiu/Swin-UMamba/assets/117509706/8beeb4ab-7ebf-4279-98ba-d3d3c5512a30)

**Comment by 1580827935** [comment]
![111](https://github.com/JiarunLiu/Swin-UMamba/assets/117509706/f489b196-47b2-4113-ae6e-b3085959ad41)
BUG! 请问这个包在哪？

**Comment by JiarunLiu** [comment]
@1580827935, `mamba_ssm`是安装在conda环境中的，你可以检查一下`mamba_ssm`是否已经正确安装，conda环境配置可参考[环境安装说明](https://github.com/JiarunLiu/Swin-UMamba?tab=readme-ov-file#installation)。另外，训练Swin-UMamba可以参考[这里](https://github.com/JiarunLiu/Swin-UMamba?tab=readme-ov-file#training)。

**Comment by 1580827935** [comment]
已跑通，非常感谢您提供帮助！祝中搞！
