### ISSUE TITLE
I want to ask why it keeping on "using pin_memory on device 0 using pin_memory on device 1"？

### ISSUE THREAD

**Issue by liyang19971022** [JiarunLiu/Swin-UMamba#6]
I want to ask why it keeping on "using pin_memory on device 0
using pin_memory on device 1"？I use two GPU and its Utilization rate is all 100%，My CPU has 32 cores but its Utilization rate is 400%。

**Comment by JiarunLiu** [comment]
Hi @liyang19971022, could you please specify the issue you're encountering? We're using the default `pin_memory` setting.
