### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by Atik-Ahamed** [JiarunLiu/Swin-UMamba#8]
Excellent work, very interesting.

While running the Swin-UMambaD from pre-trained weights, I faced the issue of key error in: https://github.com/JiarunLiu/Swin-UMamba/blob/50eecc895fe7377676f09ba45f28855a18153336/swin_umamba/nnunetv2/nets/SwinUMambaD.py#L669.
Possibly the checkpoint doesn't have the "config" key?
It would be great to have your valuable feedback in this regard.

Best,
Atik

**Comment by JiarunLiu** [comment]
Hi, @Atik-Ahamed. Thanks for your feedback. VMamba has updated their released checkpoint file and removed the `config` from it. You can try to update the codes as follows:

```python
# line 669 in SwinUMambaD.py
if "patch_embed" in k and ckpt['model']["patch_embed.proj.weight"].shape[1] != num_input_channels:
```

We will update our code release later.

**Comment by Atik-Ahamed** [comment]
Thanks a lot for your help and prompt reply.
